<?php if(count($_info = $this->getAdditionalInformation())): ?>
    <?php if(key_exists('terms', $_info)): ?>
        <b><?php echo $this->__('Betalingsbetingelser:'); ?></b> <?php echo $_info['terms']; ?><br>
    <?php endif; ?>
    <?php if(key_exists('maturitydate', $_info)): ?>
        <b><?php echo $this->__('Forfaldsdato:'); ?></b> <?php echo $_info['maturitydate']; ?><br>
    <?php endif; ?>
    <?php if(key_exists('bankname', $_info)): ?>
        <b><?php echo $this->__('Bank:'); ?></b> <?php echo $_info['bankname']; ?><br>
    <?php endif; ?>
    <b><?php echo $this->__('Reg.nr:'); ?></b> <?php echo $_info['bankid']; ?> <b><?php echo $this->__('Konto:'); ?></b> <?php echo $_info['accountid']; ?><br>
    <br>
<?php else: ?>
    <p><b>Faktura</b><br></p>
<?php endif; ?>